# Generated by Django 5.0.4 on 2024-06-25 19:47

from django.db import migrations, models


def create_unique_brands(apps, schema_editor):
    shoe_model = apps.get_model('main_app', 'Shoe')
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')

    unique_brand_names = shoe_model.objects.values_list('brand', flat=True).distinct()

    unique_brands_model.objects.bulk_create([unique_brands_model(brand_name=brand) for brand in unique_brand_names])


def reverse_create_unique_brands(apps, schema_editor):
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')
    unique_brands_model.objects.all().delete()


class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_uniquebrands'), ('main_app', '0003_migrate_unique_brands')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        ),
    ]
