# Generated by Django 5.0.4 on 2024-06-26 13:42

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    people = person_model.objects.all()

    for person in people:
        if person.age < 13:
            person.age_group = "Child"
        elif person.age < 18:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"

    person_model.objects.bulk_update(people, ['age_group'])


def reverse_set_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    people = person_model.objects.all()
    default_value = person_model._meta.get_field('age_group').default

    for person in people:
        person.age_group = default_value

    person_model.objects.bulk_update(people, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            set_age_group,
            reverse_set_age_group
        ),
    ]
