# Generated by Django 5.0.4 on 2024-06-26 14:10

from django.db import migrations


def set_price_rarity(apps, schema_editor):
    item_model = apps.get_model("main_app", "Item")
    items = item_model.objects.all()

    for item in items:
        if item.price < 11:
            item.rarity = "Rare"
        elif item.price < 21:
            item.rarity = "Very Rare"
        elif item.price < 31:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"

    item_model.objects.bulk_update(items, ['rarity'])


def reverse_set_price_rarity(apps, schema_editor):
    item_model = apps.get_model("main_app", "Item")
    items = item_model.objects.all()
    default_value = item_model._meta.get_field('rarity').default

    for item in items:
        item.rarity = default_value

    item_model.objects.bulk_update(items, ['rarity'])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            set_price_rarity,
            reverse_set_price_rarity
        )
    ]
